### ISSUE TITLE
Machine authentication to `divviup-api` API

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-api#195]
Currently, `divviup-api`'s API supports authentication via Auth0, and subsequently requests must include a `divviup.sid` cookie with a session name. This is suitable for humans navigating to https://divviup.org, but some subscribers will want to have their own dashboards make authenticated API requests to `divviup-api` to do things like create and enumerate tasks. We should add a mechanism for machines to do this.

Steps:
- [x] add ApiToken entity as described above #233 
- [x] add GET, POST, and DELETE api_token endpoints as described above #233 
- [x] add an early handler that optionally populates Account based on bearer token #233 
- [x] #271

**Comment by tgeoghegan** [comment]
It's possible that we can achieve this by federating Auth0 with a subscriber's identity system, but I believe that'd impose requirements on the subscriber's identity system like an OIDC provider we can federate with.

A simpler path forward could be to add an authenticated endpoint to `divviup-api` that mints an API token, an opaque blob that can later be presented as a bearer token in HTTP requests to act as the user that minted the token.

**Comment by jbr** [comment]
Do we want machines to authenticate as Users or as Accounts? My inclination is to make machine tokens auth directly as an Account, which is slightly different from oauth2 behavior. I was figuring we'd have an interface on the Account view that shows the timestamp and other info about active tokens and their usage and allows the deletion of existing tokens and the creation of new ones. Eventually we may want to add scopes to those tokens. I think that's the "authenticated endpoint that mints a token" but it also entails a few other endpoints like deleting a token and enumerating tokens without revealing them

**Comment by tgeoghegan** [comment]
You're right, authenticating as an account makes more sense, especially since `divviup-api` has no users table (we delegate that completely to Auth0). The API you sketched out looks good to me. There would be a corresponding persistence entity/ DB table to store the token IDs and hashes, right?

**Comment by jbr** [comment]
> There would be a corresponding persistence entity/ DB table to store the token IDs and hashes, right?

Yes, exactly.

```rust
struct ApiToken {
    account_id: Uuid,
    id: Uuid,
    token_hash: Vec<u8>,
    created_at: OffsetDateTime,
    deleted_at: OffsetDateTime, //for tombstoning?
}
```

and possibly a `created_by` email address for auditing but probably not since we don't do that elsewhere and should add that en masse at some later point

**Comment by jbr** [comment]
Steps:
- [ ] populate Account in State in addition to User
- [ ] use Account for permissions everywhere User is currently used
- [ ] add ApiToken entity as described above
- [ ] add GET, POST, and DELETE api_token endpoints as described above
- [ ] add an early handler that optionally populates Account based on bearer token
